name: test cicd
on:
  push:
    branches:
      - main

stages:
  - validate
  - plan
  - apply

variables:
  TF_VERSION: "1.10.5"
  GOOGLE_PROJECT_ID: "githubcicd-tp"
  GOOGLE_REGION: "europe-west1"

before_script:
  - echo "Authentification GCP..."
  - gcloud auth activate-service-account --key-file=${CI_PROJECT_DIR}/githubcicd-tp-5e3b61989929.json
  - gcloud config set project $GOOGLE_PROJECT_ID
  - gcloud config set compute/region $GOOGLE_REGION
  - terraform --version

jobs:
  terraform_validate:
    image: hashicorp/terraform:${TF_VERSION}
    stage: validate
    script:
      - terraform init
      - terraform fmt -check
      - terraform validate

  terraform_plan:
    image: hashicorp/terraform:${TF_VERSION}
    stage: plan
    script:
      - terraform init 
      - terraform plan 

  terraform_apply:
    image: hashicorp/terraform:${TF_VERSION}
    stage: apply
    when: manual
    script:
      - terraform apply
