name: Test déploiement CICD

on:
  push:
    branches:
      - main

env:
  GOOGLE_CREDENTIALS: ${{ secrets.SERVICE_ACCOUNT_KEY }}
  GOOGLE_PROJECT_ID: "githubcicd-tp"
  GOOGLE_REGION: "eu-west1"
  TF_VERSION: "1.10.5"
  TF_STATE_BUCKET: "tp-cicd-debacq-bucket"
  TF_STATE_FILE: "terraform.tfstate"

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authentification GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Installer Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: 🛠️ Réinitialisation de Terraform (cache)
        run: |
          rm -rf .terraform .terraform.lock.hcl
          terraform init -upgrade
        working-directory: terraform/

      - name: Initialisation de Terraform
        run: terraform init -backend-config="bucket=${TF_STATE_BUCKET}" -backend-config="prefix=${TF_STATE_FILE}"

      - name: Vérification Terraform
        run: terraform validate
        working-directory: terraform/

      - name: Plan Terraform
        run: terraform plan -out=tfplan
        working-directory: terraform/

      - name: Appliquer Terraform (Manual Approval)
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
        working-directory: terraform/
